// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class USCPEApiDTOCaoAppsParent
    {
        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsParent class.
        /// </summary>
        public USCPEApiDTOCaoAppsParent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsParent class.
        /// </summary>
        public USCPEApiDTOCaoAppsParent(USCPEApiDTOCaoAppsAddress address = default(USCPEApiDTOCaoAppsAddress), IList<USCPEApiDTOCaoAppsParentCollege> colleges = default(IList<USCPEApiDTOCaoAppsParentCollege>), int? parentId = default(int?), string type = default(string), string caoParentPrefix = default(string), string marriedTo = default(string), bool? isStepParent = default(bool?), bool? isLegalGuard = default(bool?), bool? isAlive = default(bool?), System.DateTime? deceasedDate = default(System.DateTime?), string title = default(string), string firstName = default(string), string middleName = default(string), string lastName = default(string), string suffix = default(string), string countryOfBirth = default(string), string email = default(string), string phoneType = default(string), string phone = default(string), string occupation = default(string), string emplStatus = default(string), string positionTitle = default(string), string employedByUniv = default(string), string employer = default(string), string employedUnivCeeb = default(string), string employedUnivName = default(string), string employedUnivType = default(string), string educationLevel = default(string), string formerName = default(string))
        {
            Address = address;
            Colleges = colleges;
            ParentId = parentId;
            Type = type;
            CaoParentPrefix = caoParentPrefix;
            MarriedTo = marriedTo;
            IsStepParent = isStepParent;
            IsLegalGuard = isLegalGuard;
            IsAlive = isAlive;
            DeceasedDate = deceasedDate;
            Title = title;
            FirstName = firstName;
            MiddleName = middleName;
            LastName = lastName;
            Suffix = suffix;
            CountryOfBirth = countryOfBirth;
            Email = email;
            PhoneType = phoneType;
            Phone = phone;
            Occupation = occupation;
            EmplStatus = emplStatus;
            PositionTitle = positionTitle;
            EmployedByUniv = employedByUniv;
            Employer = employer;
            EmployedUnivCeeb = employedUnivCeeb;
            EmployedUnivName = employedUnivName;
            EmployedUnivType = employedUnivType;
            EducationLevel = educationLevel;
            FormerName = formerName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public USCPEApiDTOCaoAppsAddress Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "colleges")]
        public IList<USCPEApiDTOCaoAppsParentCollege> Colleges { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentId")]
        public int? ParentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "caoParentPrefix")]
        public string CaoParentPrefix { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "marriedTo")]
        public string MarriedTo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isStepParent")]
        public bool? IsStepParent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isLegalGuard")]
        public bool? IsLegalGuard { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isAlive")]
        public bool? IsAlive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deceasedDate")]
        public System.DateTime? DeceasedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "middleName")]
        public string MiddleName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "suffix")]
        public string Suffix { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "countryOfBirth")]
        public string CountryOfBirth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phoneType")]
        public string PhoneType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "occupation")]
        public string Occupation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emplStatus")]
        public string EmplStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "positionTitle")]
        public string PositionTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "employedByUniv")]
        public string EmployedByUniv { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "employer")]
        public string Employer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "employedUnivCeeb")]
        public string EmployedUnivCeeb { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "employedUnivName")]
        public string EmployedUnivName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "employedUnivType")]
        public string EmployedUnivType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "educationLevel")]
        public string EducationLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "formerName")]
        public string FormerName { get; set; }

    }
}
