// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class USCPEApiDTOExploreHostingApplication
    {
        /// <summary>
        /// Initializes a new instance of the
        /// USCPEApiDTOExploreHostingApplication class.
        /// </summary>
        public USCPEApiDTOExploreHostingApplication()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// USCPEApiDTOExploreHostingApplication class.
        /// </summary>
        public USCPEApiDTOExploreHostingApplication(double? id = default(double?), string year = default(string), double? trainingId = default(double?), USCPEApiDTOCommonPhone cellPhone = default(USCPEApiDTOCommonPhone), double? buildingId = default(double?), string buildingCode = default(string), string buildingName = default(string), string roomNumber = default(string), string homeState = default(string), bool? academicProbationFlag = default(bool?), bool? disciplinaryActionFlag = default(bool?), System.DateTime? sjacsDate = default(System.DateTime?), string sjacsExplenation = default(string), string howDidYouHere = default(string), bool? roomMateExploreUscFlag = default(bool?), string roomMateName = default(string), string roomMateEmail = default(string), bool? agreementFlag = default(bool?), bool? excludeHostMatchFlag = default(bool?), string notes = default(string), string stateCode = default(string), string countryCode = default(string), bool? trainingFlag = default(bool?), string preferredMajor = default(string), System.DateTime? modifyDate = default(System.DateTime?), IList<USCPEApiDTOExploreHostingApplicationEvent> events = default(IList<USCPEApiDTOExploreHostingApplicationEvent>))
        {
            Id = id;
            Year = year;
            TrainingId = trainingId;
            CellPhone = cellPhone;
            BuildingId = buildingId;
            BuildingCode = buildingCode;
            BuildingName = buildingName;
            RoomNumber = roomNumber;
            HomeState = homeState;
            AcademicProbationFlag = academicProbationFlag;
            DisciplinaryActionFlag = disciplinaryActionFlag;
            SjacsDate = sjacsDate;
            SjacsExplenation = sjacsExplenation;
            HowDidYouHere = howDidYouHere;
            RoomMateExploreUscFlag = roomMateExploreUscFlag;
            RoomMateName = roomMateName;
            RoomMateEmail = roomMateEmail;
            AgreementFlag = agreementFlag;
            ExcludeHostMatchFlag = excludeHostMatchFlag;
            Notes = notes;
            StateCode = stateCode;
            CountryCode = countryCode;
            TrainingFlag = trainingFlag;
            PreferredMajor = preferredMajor;
            ModifyDate = modifyDate;
            Events = events;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public double? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "year")]
        public string Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trainingId")]
        public double? TrainingId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cellPhone")]
        public USCPEApiDTOCommonPhone CellPhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildingId")]
        public double? BuildingId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildingCode")]
        public string BuildingCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buildingName")]
        public string BuildingName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roomNumber")]
        public string RoomNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "homeState")]
        public string HomeState { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "academicProbationFlag")]
        public bool? AcademicProbationFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "disciplinaryActionFlag")]
        public bool? DisciplinaryActionFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sjacsDate")]
        public System.DateTime? SjacsDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sjacsExplenation")]
        public string SjacsExplenation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "howDidYouHere")]
        public string HowDidYouHere { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roomMateExploreUscFlag")]
        public bool? RoomMateExploreUscFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roomMateName")]
        public string RoomMateName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roomMateEmail")]
        public string RoomMateEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "agreementFlag")]
        public bool? AgreementFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "excludeHostMatchFlag")]
        public bool? ExcludeHostMatchFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "notes")]
        public string Notes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stateCode")]
        public string StateCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "countryCode")]
        public string CountryCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "trainingFlag")]
        public bool? TrainingFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "preferredMajor")]
        public string PreferredMajor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifyDate")]
        public System.DateTime? ModifyDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "events")]
        public IList<USCPEApiDTOExploreHostingApplicationEvent> Events { get; set; }

    }
}
