// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class USCPEApiDTOReportAccessPermission
    {
        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOReportAccessPermission
        /// class.
        /// </summary>
        public USCPEApiDTOReportAccessPermission()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOReportAccessPermission
        /// class.
        /// </summary>
        public USCPEApiDTOReportAccessPermission(int? id = default(int?), string code = default(string), string scope = default(string), string graduateFlag = default(string), string subDomain = default(string), string grantedBy = default(string), System.DateTime? grantedTime = default(System.DateTime?), string revokedBy = default(string), System.DateTime? revokedTime = default(System.DateTime?))
        {
            Id = id;
            Code = code;
            Scope = scope;
            GraduateFlag = graduateFlag;
            SubDomain = subDomain;
            GrantedBy = grantedBy;
            GrantedTime = grantedTime;
            RevokedBy = revokedBy;
            RevokedTime = revokedTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scope")]
        public string Scope { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "graduateFlag")]
        public string GraduateFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subDomain")]
        public string SubDomain { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "grantedBy")]
        public string GrantedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "grantedTime")]
        public System.DateTime? GrantedTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "revokedBy")]
        public string RevokedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "revokedTime")]
        public System.DateTime? RevokedTime { get; set; }

    }
}
