// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class USCPEApiWebApiAreasWebAdmitModelsVAPPLICATIONPROGRAM
    {
        /// <summary>
        /// Initializes a new instance of the
        /// USCPEApiWebApiAreasWebAdmitModelsVAPPLICATIONPROGRAM class.
        /// </summary>
        public USCPEApiWebApiAreasWebAdmitModelsVAPPLICATIONPROGRAM()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// USCPEApiWebApiAreasWebAdmitModelsVAPPLICATIONPROGRAM class.
        /// </summary>
        public USCPEApiWebApiAreasWebAdmitModelsVAPPLICATIONPROGRAM(string caSID = default(string), string associatioNNAME = default(string), string cyclENAME = default(string), int? sQNUMBER = default(int?), string dPROGRAMLOOKUPID = default(string), string prograMCODE = default(string), string description = default(string), string dPROGRAMSTARTTERM = default(string), string dPROGRAMSTARTYEAR = default(string), string dPROGRAMLEVEL = default(string), string dDEPARTMENTNAME = default(string), string dTRACK = default(string), string dDELIVERY = default(string), string applicatioNSTATUS = default(string), System.DateTime? crtDINCNCLTS = default(System.DateTime?), string crtDBYSRCSYS = default(string), string crtDBYSRCOPER = default(string), System.DateTime? lasTUPDTTS = default(System.DateTime?), string lasTUPDTBYSRCSYS = default(string), string lasTUPDTBYSRCOPER = default(string), System.DateTime? invaliDTS = default(System.DateTime?), string invaliDBYOPER = default(string), string designation = default(string), USCPEApiWebApiAreasWebAdmitModelsVFULLAPPLICATION vFULLAPPLICATION = default(USCPEApiWebApiAreasWebAdmitModelsVFULLAPPLICATION))
        {
            CaSID = caSID;
            AssociatioNNAME = associatioNNAME;
            CyclENAME = cyclENAME;
            SQNUMBER = sQNUMBER;
            DPROGRAMLOOKUPID = dPROGRAMLOOKUPID;
            PrograMCODE = prograMCODE;
            Description = description;
            DPROGRAMSTARTTERM = dPROGRAMSTARTTERM;
            DPROGRAMSTARTYEAR = dPROGRAMSTARTYEAR;
            DPROGRAMLEVEL = dPROGRAMLEVEL;
            DDEPARTMENTNAME = dDEPARTMENTNAME;
            DTRACK = dTRACK;
            DDELIVERY = dDELIVERY;
            ApplicatioNSTATUS = applicatioNSTATUS;
            CrtDINCNCLTS = crtDINCNCLTS;
            CrtDBYSRCSYS = crtDBYSRCSYS;
            CrtDBYSRCOPER = crtDBYSRCOPER;
            LasTUPDTTS = lasTUPDTTS;
            LasTUPDTBYSRCSYS = lasTUPDTBYSRCSYS;
            LasTUPDTBYSRCOPER = lasTUPDTBYSRCOPER;
            InvaliDTS = invaliDTS;
            InvaliDBYOPER = invaliDBYOPER;
            Designation = designation;
            VFULLAPPLICATION = vFULLAPPLICATION;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "caS_ID")]
        public string CaSID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "associatioN_NAME")]
        public string AssociatioNNAME { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cyclE_NAME")]
        public string CyclENAME { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sQ_NUMBER")]
        public int? SQNUMBER { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "d_PROGRAM_LOOKUP_ID")]
        public string DPROGRAMLOOKUPID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prograM_CODE")]
        public string PrograMCODE { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "d_PROGRAM_START_TERM")]
        public string DPROGRAMSTARTTERM { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "d_PROGRAM_START_YEAR")]
        public string DPROGRAMSTARTYEAR { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "d_PROGRAM_LEVEL")]
        public string DPROGRAMLEVEL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "d_DEPARTMENT_NAME")]
        public string DDEPARTMENTNAME { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "d_TRACK")]
        public string DTRACK { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "d_DELIVERY")]
        public string DDELIVERY { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicatioN_STATUS")]
        public string ApplicatioNSTATUS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crtD_IN_CNCL_TS")]
        public System.DateTime? CrtDINCNCLTS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crtD_BY_SRC_SYS")]
        public string CrtDBYSRCSYS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crtD_BY_SRC_OPER")]
        public string CrtDBYSRCOPER { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lasT_UPDT_TS")]
        public System.DateTime? LasTUPDTTS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lasT_UPDT_BY_SRC_SYS")]
        public string LasTUPDTBYSRCSYS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lasT_UPDT_BY_SRC_OPER")]
        public string LasTUPDTBYSRCOPER { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "invaliD_TS")]
        public System.DateTime? InvaliDTS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "invaliD_BY_OPER")]
        public string InvaliDBYOPER { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designation")]
        public string Designation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "v_FULL_APPLICATION")]
        public USCPEApiWebApiAreasWebAdmitModelsVFULLAPPLICATION VFULLAPPLICATION { get; set; }

    }
}
