// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class USCPEApiDTOCaoAppsSibling
    {
        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsSibling class.
        /// </summary>
        public USCPEApiDTOCaoAppsSibling()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsSibling class.
        /// </summary>
        public USCPEApiDTOCaoAppsSibling(int? siblingId = default(int?), string firstName = default(string), string middleName = default(string), string lastName = default(string), string otherLastName = default(string), bool? hasAppliedUsc = default(bool?), int? age = default(int?), string relationship = default(string), string gradeLevel = default(string), string degree = default(string), string college = default(string), string collegeCeeb = default(string), System.DateTime? fromDate = default(System.DateTime?), System.DateTime? toDate = default(System.DateTime?))
        {
            SiblingId = siblingId;
            FirstName = firstName;
            MiddleName = middleName;
            LastName = lastName;
            OtherLastName = otherLastName;
            HasAppliedUsc = hasAppliedUsc;
            Age = age;
            Relationship = relationship;
            GradeLevel = gradeLevel;
            Degree = degree;
            College = college;
            CollegeCeeb = collegeCeeb;
            FromDate = fromDate;
            ToDate = toDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "siblingId")]
        public int? SiblingId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "middleName")]
        public string MiddleName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "otherLastName")]
        public string OtherLastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasAppliedUsc")]
        public bool? HasAppliedUsc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "age")]
        public int? Age { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relationship")]
        public string Relationship { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gradeLevel")]
        public string GradeLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "degree")]
        public string Degree { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "college")]
        public string College { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "collegeCeeb")]
        public string CollegeCeeb { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fromDate")]
        public System.DateTime? FromDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "toDate")]
        public System.DateTime? ToDate { get; set; }

    }
}
