// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class USCPEApiDTOCaoAppsCourse
    {
        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsCourse class.
        /// </summary>
        public USCPEApiDTOCaoAppsCourse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsCourse class.
        /// </summary>
        public USCPEApiDTOCaoAppsCourse(int? courseId = default(int?), string title = default(string), string courseLevel = default(string), string schedule = default(string))
        {
            CourseId = courseId;
            Title = title;
            CourseLevel = courseLevel;
            Schedule = schedule;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "courseId")]
        public int? CourseId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "courseLevel")]
        public string CourseLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schedule")]
        public string Schedule { get; set; }

    }
}
