// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class USCPEApiWebApiAreasWebAdmitModelsAPPLICATIONPROGRAM
    {
        /// <summary>
        /// Initializes a new instance of the
        /// USCPEApiWebApiAreasWebAdmitModelsAPPLICATIONPROGRAM class.
        /// </summary>
        public USCPEApiWebApiAreasWebAdmitModelsAPPLICATIONPROGRAM()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// USCPEApiWebApiAreasWebAdmitModelsAPPLICATIONPROGRAM class.
        /// </summary>
        public USCPEApiWebApiAreasWebAdmitModelsAPPLICATIONPROGRAM(string caSID = default(string), string associatioNNAME = default(string), string cyclENAME = default(string), int? sQNUMBER = default(int?), string designatioNPROGRAMLOOKUPID = default(string), string prograMCODE = default(string), string designatioNPROGRAMSTARTTERM = default(string), string designatioNPROGRAMSTARTYEAR = default(string), string designatioNPROGRAMLEVEL = default(string), string designatioNDEPARTMENTNAME = default(string), string designatioNTRACK = default(string), string designatioNDELIVERY = default(string), string applicatioNSTATUS = default(string), System.DateTime? crtDINCNCLTS = default(System.DateTime?), string crtDBYSRCSYS = default(string), string crtDBYSRCOPER = default(string), System.DateTime? lasTUPDTTS = default(System.DateTime?), string lasTUPDTBYSRCSYS = default(string), string lasTUPDTBYSRCOPER = default(string), System.DateTime? invaliDTS = default(System.DateTime?), string invaliDBYOPER = default(string), string designation = default(string), string internaLPROGRAMID = default(string), string designatioNORGANIZATION = default(string), USCPEApiWebApiAreasWebAdmitModelsAPPLICATIONLOAD applicatioNLOAD = default(USCPEApiWebApiAreasWebAdmitModelsAPPLICATIONLOAD), USCPEApiWebApiAreasWebAdmitModelsVAPPLICATIONLOAD vAPPLICATIONLOAD = default(USCPEApiWebApiAreasWebAdmitModelsVAPPLICATIONLOAD), USCPEApiWebApiAreasWebAdmitModelsVFULLAPPLICATION vFULLAPPLICATION = default(USCPEApiWebApiAreasWebAdmitModelsVFULLAPPLICATION))
        {
            CaSID = caSID;
            AssociatioNNAME = associatioNNAME;
            CyclENAME = cyclENAME;
            SQNUMBER = sQNUMBER;
            DesignatioNPROGRAMLOOKUPID = designatioNPROGRAMLOOKUPID;
            PrograMCODE = prograMCODE;
            DesignatioNPROGRAMSTARTTERM = designatioNPROGRAMSTARTTERM;
            DesignatioNPROGRAMSTARTYEAR = designatioNPROGRAMSTARTYEAR;
            DesignatioNPROGRAMLEVEL = designatioNPROGRAMLEVEL;
            DesignatioNDEPARTMENTNAME = designatioNDEPARTMENTNAME;
            DesignatioNTRACK = designatioNTRACK;
            DesignatioNDELIVERY = designatioNDELIVERY;
            ApplicatioNSTATUS = applicatioNSTATUS;
            CrtDINCNCLTS = crtDINCNCLTS;
            CrtDBYSRCSYS = crtDBYSRCSYS;
            CrtDBYSRCOPER = crtDBYSRCOPER;
            LasTUPDTTS = lasTUPDTTS;
            LasTUPDTBYSRCSYS = lasTUPDTBYSRCSYS;
            LasTUPDTBYSRCOPER = lasTUPDTBYSRCOPER;
            InvaliDTS = invaliDTS;
            InvaliDBYOPER = invaliDBYOPER;
            Designation = designation;
            InternaLPROGRAMID = internaLPROGRAMID;
            DesignatioNORGANIZATION = designatioNORGANIZATION;
            ApplicatioNLOAD = applicatioNLOAD;
            VAPPLICATIONLOAD = vAPPLICATIONLOAD;
            VFULLAPPLICATION = vFULLAPPLICATION;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "caS_ID")]
        public string CaSID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "associatioN_NAME")]
        public string AssociatioNNAME { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cyclE_NAME")]
        public string CyclENAME { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sQ_NUMBER")]
        public int? SQNUMBER { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designatioN_PROGRAM_LOOKUP_ID")]
        public string DesignatioNPROGRAMLOOKUPID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prograM_CODE")]
        public string PrograMCODE { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designatioN_PROGRAM_START_TERM")]
        public string DesignatioNPROGRAMSTARTTERM { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designatioN_PROGRAM_START_YEAR")]
        public string DesignatioNPROGRAMSTARTYEAR { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designatioN_PROGRAM_LEVEL")]
        public string DesignatioNPROGRAMLEVEL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designatioN_DEPARTMENT_NAME")]
        public string DesignatioNDEPARTMENTNAME { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designatioN_TRACK")]
        public string DesignatioNTRACK { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designatioN_DELIVERY")]
        public string DesignatioNDELIVERY { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicatioN_STATUS")]
        public string ApplicatioNSTATUS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crtD_IN_CNCL_TS")]
        public System.DateTime? CrtDINCNCLTS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crtD_BY_SRC_SYS")]
        public string CrtDBYSRCSYS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crtD_BY_SRC_OPER")]
        public string CrtDBYSRCOPER { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lasT_UPDT_TS")]
        public System.DateTime? LasTUPDTTS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lasT_UPDT_BY_SRC_SYS")]
        public string LasTUPDTBYSRCSYS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lasT_UPDT_BY_SRC_OPER")]
        public string LasTUPDTBYSRCOPER { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "invaliD_TS")]
        public System.DateTime? InvaliDTS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "invaliD_BY_OPER")]
        public string InvaliDBYOPER { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designation")]
        public string Designation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "internaL_PROGRAM_ID")]
        public string InternaLPROGRAMID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "designatioN_ORGANIZATION")]
        public string DesignatioNORGANIZATION { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicatioN_LOAD")]
        public USCPEApiWebApiAreasWebAdmitModelsAPPLICATIONLOAD ApplicatioNLOAD { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "v_APPLICATION_LOAD")]
        public USCPEApiWebApiAreasWebAdmitModelsVAPPLICATIONLOAD VAPPLICATIONLOAD { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "v_FULL_APPLICATION")]
        public USCPEApiWebApiAreasWebAdmitModelsVFULLAPPLICATION VFULLAPPLICATION { get; set; }

    }
}
