// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class USCPEApiDTOCaoAppsSchoolContact
    {
        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsSchoolContact
        /// class.
        /// </summary>
        public USCPEApiDTOCaoAppsSchoolContact()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsSchoolContact
        /// class.
        /// </summary>
        public USCPEApiDTOCaoAppsSchoolContact(string prefix = default(string), string firstName = default(string), string middleInit = default(string), string lastName = default(string), string title = default(string), string email = default(string), string phone = default(string))
        {
            Prefix = prefix;
            FirstName = firstName;
            MiddleInit = middleInit;
            LastName = lastName;
            Title = title;
            Email = email;
            Phone = phone;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prefix")]
        public string Prefix { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "middleInit")]
        public string MiddleInit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; set; }

    }
}
