// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class USCPEApiDTOCaoAppsSslExam
    {
        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsSslExam class.
        /// </summary>
        public USCPEApiDTOCaoAppsSslExam()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsSslExam class.
        /// </summary>
        public USCPEApiDTOCaoAppsSslExam(double? sslExamId = default(double?), System.DateTime? examDate = default(System.DateTime?), string board = default(string), string boardOther = default(string), string subject = default(string), string score = default(string), string scoreType = default(string))
        {
            SslExamId = sslExamId;
            ExamDate = examDate;
            Board = board;
            BoardOther = boardOther;
            Subject = subject;
            Score = score;
            ScoreType = scoreType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sslExamId")]
        public double? SslExamId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "examDate")]
        public System.DateTime? ExamDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "board")]
        public string Board { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "boardOther")]
        public string BoardOther { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subject")]
        public string Subject { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public string Score { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scoreType")]
        public string ScoreType { get; set; }

    }
}
