// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class USCPEApiDTOCaoAppsCollegeCredit
    {
        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsCollegeCredit
        /// class.
        /// </summary>
        public USCPEApiDTOCaoAppsCollegeCredit()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsCollegeCredit
        /// class.
        /// </summary>
        public USCPEApiDTOCaoAppsCollegeCredit(int? collegeCreditId = default(int?), string city = default(string), string state = default(string), string zipcode = default(string), string country = default(string), string collegeCeeb = default(string), string name = default(string), string type = default(string), string course = default(string), System.DateTime? fromDate = default(System.DateTime?), System.DateTime? toDate = default(System.DateTime?), string degree = default(string))
        {
            CollegeCreditId = collegeCreditId;
            City = city;
            State = state;
            Zipcode = zipcode;
            Country = country;
            CollegeCeeb = collegeCeeb;
            Name = name;
            Type = type;
            Course = course;
            FromDate = fromDate;
            ToDate = toDate;
            Degree = degree;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "collegeCreditId")]
        public int? CollegeCreditId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zipcode")]
        public string Zipcode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "collegeCeeb")]
        public string CollegeCeeb { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "course")]
        public string Course { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fromDate")]
        public System.DateTime? FromDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "toDate")]
        public System.DateTime? ToDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "degree")]
        public string Degree { get; set; }

    }
}
