// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class USCPEApiDTORnrAppsBursarTerm
    {
        /// <summary>
        /// Initializes a new instance of the USCPEApiDTORnrAppsBursarTerm
        /// class.
        /// </summary>
        public USCPEApiDTORnrAppsBursarTerm()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the USCPEApiDTORnrAppsBursarTerm
        /// class.
        /// </summary>
        public USCPEApiDTORnrAppsBursarTerm(string uscId = default(string), string term = default(string), System.DateTime? insuranceDate = default(System.DateTime?), bool? hasInsurance = default(bool?), string insuranceOper = default(string), System.DateTime? tfCalculateDate = default(System.DateTime?), double? tfUnits = default(double?), System.DateTime? updateDate = default(System.DateTime?))
        {
            UscId = uscId;
            Term = term;
            InsuranceDate = insuranceDate;
            HasInsurance = hasInsurance;
            InsuranceOper = insuranceOper;
            TfCalculateDate = tfCalculateDate;
            TfUnits = tfUnits;
            UpdateDate = updateDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uscId")]
        public string UscId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "term")]
        public string Term { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "insuranceDate")]
        public System.DateTime? InsuranceDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasInsurance")]
        public bool? HasInsurance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "insuranceOper")]
        public string InsuranceOper { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tfCalculateDate")]
        public System.DateTime? TfCalculateDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tfUnits")]
        public double? TfUnits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updateDate")]
        public System.DateTime? UpdateDate { get; set; }

    }
}
