// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class USCPEApiDTOExploreHostingMatch
    {
        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOExploreHostingMatch
        /// class.
        /// </summary>
        public USCPEApiDTOExploreHostingMatch()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOExploreHostingMatch
        /// class.
        /// </summary>
        public USCPEApiDTOExploreHostingMatch(double? id = default(double?), bool? leftEarlyFlag = default(bool?), bool? noShowFlag = default(bool?), System.DateTime? modifyDate = default(System.DateTime?), USCPEApiDTOExploreHostingHost overnightHost = default(USCPEApiDTOExploreHostingHost), string overnightHostSpecialCode = default(string), USCPEApiDTOExploreHostingHost dinnerHost = default(USCPEApiDTOExploreHostingHost), string dinnerHostSpecialCode = default(string), USCPEApiDTOExploreHostingHost prenightHost = default(USCPEApiDTOExploreHostingHost), string prenightHostSpecialCode = default(string))
        {
            Id = id;
            LeftEarlyFlag = leftEarlyFlag;
            NoShowFlag = noShowFlag;
            ModifyDate = modifyDate;
            OvernightHost = overnightHost;
            OvernightHostSpecialCode = overnightHostSpecialCode;
            DinnerHost = dinnerHost;
            DinnerHostSpecialCode = dinnerHostSpecialCode;
            PrenightHost = prenightHost;
            PrenightHostSpecialCode = prenightHostSpecialCode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public double? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "leftEarlyFlag")]
        public bool? LeftEarlyFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "noShowFlag")]
        public bool? NoShowFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifyDate")]
        public System.DateTime? ModifyDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overnightHost")]
        public USCPEApiDTOExploreHostingHost OvernightHost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overnightHostSpecialCode")]
        public string OvernightHostSpecialCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dinnerHost")]
        public USCPEApiDTOExploreHostingHost DinnerHost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dinnerHostSpecialCode")]
        public string DinnerHostSpecialCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prenightHost")]
        public USCPEApiDTOExploreHostingHost PrenightHost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prenightHostSpecialCode")]
        public string PrenightHostSpecialCode { get; set; }

    }
}
