// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class USCPEApiDTOCaoAppsFamilyAttend
    {
        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsFamilyAttend
        /// class.
        /// </summary>
        public USCPEApiDTOCaoAppsFamilyAttend()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the USCPEApiDTOCaoAppsFamilyAttend
        /// class.
        /// </summary>
        public USCPEApiDTOCaoAppsFamilyAttend(IList<USCPEApiDTOCaoAppsFamilyAttendDegree> degrees = default(IList<USCPEApiDTOCaoAppsFamilyAttendDegree>), int? familyAttendId = default(int?), string relationship = default(string), string firstName = default(string), string lastName = default(string), string maidenName = default(string))
        {
            Degrees = degrees;
            FamilyAttendId = familyAttendId;
            Relationship = relationship;
            FirstName = firstName;
            LastName = lastName;
            MaidenName = maidenName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "degrees")]
        public IList<USCPEApiDTOCaoAppsFamilyAttendDegree> Degrees { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "familyAttendId")]
        public int? FamilyAttendId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relationship")]
        public string Relationship { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maidenName")]
        public string MaidenName { get; set; }

    }
}
