// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Advancement.
    /// </summary>
    public static partial class AdvancementExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='start'>
            /// </param>
            /// <param name='end'>
            /// </param>
            public static object GetApplicantsByLastModified(this IAdvancement operations, System.DateTime start, System.DateTime end)
            {
                return operations.GetApplicantsByLastModifiedAsync(start, end).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='start'>
            /// </param>
            /// <param name='end'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetApplicantsByLastModifiedAsync(this IAdvancement operations, System.DateTime start, System.DateTime end, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetApplicantsByLastModifiedWithHttpMessagesAsync(start, end, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
