// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PeApi
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for AgingReports.
    /// </summary>
    public static partial class AgingReportsExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='type'>
            /// Possible values include: 'Aging', 'InReview', 'AgingDataByType',
            /// 'AgingDataByFlags', 'InReviewData', 'InReviewLackData'
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='flags'>
            /// </param>
            public static object Get(this IAgingReports operations, string type, string year, string flags = default(string))
            {
                return operations.GetAsync(type, year, flags).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='type'>
            /// Possible values include: 'Aging', 'InReview', 'AgingDataByType',
            /// 'AgingDataByFlags', 'InReviewData', 'InReviewLackData'
            /// </param>
            /// <param name='year'>
            /// </param>
            /// <param name='flags'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetAsync(this IAgingReports operations, string type, string year, string flags = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(type, year, flags, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
