// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace UvApi.RnrSWebSess.Client
{
    using Newtonsoft.Json;
    using UvApi.RnrSWebSess;

    /// <summary>
    /// </summary>
    public partial interface IUvApiClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IRnrSWebSess.
        /// </summary>
        IRnrSWebSess RnrSWebSess { get; }

    }
}
