// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DataApi
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for DocumentQueues.
    /// </summary>
    public static partial class DocumentQueuesExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queueStatus'>
            /// Possible values include: 'Sent', 'NotSent'
            /// </param>
            public static object GetPdfQueueByQueueStatus(this IDocumentQueues operations, string queueStatus = default(string))
            {
                return operations.GetPdfQueueByQueueStatusAsync(queueStatus).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queueStatus'>
            /// Possible values include: 'Sent', 'NotSent'
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetPdfQueueByQueueStatusAsync(this IDocumentQueues operations, string queueStatus = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetPdfQueueByQueueStatusWithHttpMessagesAsync(queueStatus, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
