// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DataApiClient
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for DocumentQueues.
    /// </summary>
    public static partial class DocumentQueuesExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queueStatus'>
            /// Possible values include: 'Sent', 'NotSent'
            /// </param>
            public static object GetPdfQueueByQueueStatus(this IDocumentQueues operations, string queueStatus = default(string))
            {
                return Task.Factory.StartNew(s => ((IDocumentQueues)s).GetPdfQueueByQueueStatusAsync(queueStatus), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queueStatus'>
            /// Possible values include: 'Sent', 'NotSent'
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetPdfQueueByQueueStatusAsync(this IDocumentQueues operations, string queueStatus = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetPdfQueueByQueueStatusWithHttpMessagesAsync(queueStatus, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
