// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DataApiClient
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// </summary>
    public partial interface IDataAPI : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IApplicants.
        /// </summary>
        IApplicants Applicants { get; }

        /// <summary>
        /// Gets the IApplications.
        /// </summary>
        IApplications Applications { get; }

        /// <summary>
        /// Gets the ICeebLookups.
        /// </summary>
        ICeebLookups CeebLookups { get; }

        /// <summary>
        /// Gets the IControlRecords.
        /// </summary>
        IControlRecords ControlRecords { get; }

        /// <summary>
        /// Gets the IDocumentQueues.
        /// </summary>
        IDocumentQueues DocumentQueues { get; }

        /// <summary>
        /// Gets the IDocumentTypes.
        /// </summary>
        IDocumentTypes DocumentTypes { get; }

        /// <summary>
        /// Gets the IErrorTexts.
        /// </summary>
        IErrorTexts ErrorTexts { get; }

        /// <summary>
        /// Gets the IFlags.
        /// </summary>
        IFlags Flags { get; }

        /// <summary>
        /// Gets the IGroups.
        /// </summary>
        IGroups Groups { get; }

        /// <summary>
        /// Gets the IHousingOptions.
        /// </summary>
        IHousingOptions HousingOptions { get; }

        /// <summary>
        /// Gets the IIdLookups.
        /// </summary>
        IIdLookups IdLookups { get; }

        /// <summary>
        /// Gets the IOrientationOptions.
        /// </summary>
        IOrientationOptions OrientationOptions { get; }

        /// <summary>
        /// Gets the IParents.
        /// </summary>
        IParents Parents { get; }

        /// <summary>
        /// Gets the IPayments.
        /// </summary>
        IPayments Payments { get; }

        /// <summary>
        /// Gets the IPdfInfos.
        /// </summary>
        IPdfInfos PdfInfos { get; }

        /// <summary>
        /// Gets the ISessionRequest.
        /// </summary>
        ISessionRequest SessionRequest { get; }

        /// <summary>
        /// Gets the IUsers.
        /// </summary>
        IUsers Users { get; }

    }
}
