// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DataApiClient
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for Parents.
    /// </summary>
    public static partial class ParentsExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static object Get(this IParents operations)
            {
                return Task.Factory.StartNew(s => ((IParents)s).GetAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetAsync(this IParents operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='applicantUscId'>
            /// </param>
            public static object GetByApplicantUscId(this IParents operations, string applicantUscId)
            {
                return Task.Factory.StartNew(s => ((IParents)s).GetByApplicantUscIdAsync(applicantUscId), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='applicantUscId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetByApplicantUscIdAsync(this IParents operations, string applicantUscId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetByApplicantUscIdWithHttpMessagesAsync(applicantUscId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='applicantUscId'>
            /// </param>
            /// <param name='parent'>
            /// </param>
            public static object PostByApplicantUscIdParent(this IParents operations, string applicantUscId, Parent parent)
            {
                return Task.Factory.StartNew(s => ((IParents)s).PostByApplicantUscIdParentAsync(applicantUscId, parent), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='applicantUscId'>
            /// </param>
            /// <param name='parent'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PostByApplicantUscIdParentAsync(this IParents operations, string applicantUscId, Parent parent, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostByApplicantUscIdParentWithHttpMessagesAsync(applicantUscId, parent, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='parentId'>
            /// </param>
            public static object GetByParentId(this IParents operations, int parentId)
            {
                return Task.Factory.StartNew(s => ((IParents)s).GetByParentIdAsync(parentId), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='parentId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetByParentIdAsync(this IParents operations, int parentId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetByParentIdWithHttpMessagesAsync(parentId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='applicantUscId'>
            /// </param>
            /// <param name='parentId'>
            /// </param>
            public static object GetByApplicantUscIdParentId(this IParents operations, string applicantUscId, int parentId)
            {
                return Task.Factory.StartNew(s => ((IParents)s).GetByApplicantUscIdParentIdAsync(applicantUscId, parentId), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='applicantUscId'>
            /// </param>
            /// <param name='parentId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetByApplicantUscIdParentIdAsync(this IParents operations, string applicantUscId, int parentId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetByApplicantUscIdParentIdWithHttpMessagesAsync(applicantUscId, parentId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='applicantUscId'>
            /// </param>
            /// <param name='parentId'>
            /// </param>
            /// <param name='parent'>
            /// </param>
            public static object PutByApplicantUscIdParentIdParent(this IParents operations, string applicantUscId, int parentId, Parent parent)
            {
                return Task.Factory.StartNew(s => ((IParents)s).PutByApplicantUscIdParentIdParentAsync(applicantUscId, parentId, parent), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='applicantUscId'>
            /// </param>
            /// <param name='parentId'>
            /// </param>
            /// <param name='parent'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PutByApplicantUscIdParentIdParentAsync(this IParents operations, string applicantUscId, int parentId, Parent parent, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PutByApplicantUscIdParentIdParentWithHttpMessagesAsync(applicantUscId, parentId, parent, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='applicantUscId'>
            /// </param>
            /// <param name='parentId'>
            /// </param>
            public static object DeleteByApplicantUscIdParentId(this IParents operations, string applicantUscId, int parentId)
            {
                return Task.Factory.StartNew(s => ((IParents)s).DeleteByApplicantUscIdParentIdAsync(applicantUscId, parentId), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='applicantUscId'>
            /// </param>
            /// <param name='parentId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> DeleteByApplicantUscIdParentIdAsync(this IParents operations, string applicantUscId, int parentId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DeleteByApplicantUscIdParentIdWithHttpMessagesAsync(applicantUscId, parentId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
