// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DataApi
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for Users.
    /// </summary>
    public static partial class UsersExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='uscId'>
            /// </param>
            public static object GetByuscId(this IUsers operations, string uscId)
            {
                return Task.Factory.StartNew(s => ((IUsers)s).GetByuscIdAsync(uscId), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='uscId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetByuscIdAsync(this IUsers operations, string uscId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetByuscIdWithHttpMessagesAsync(uscId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='uscId'>
            /// </param>
            /// <param name='user'>
            /// </param>
            public static object PutByuscIduser(this IUsers operations, string uscId, FaoUser user)
            {
                return Task.Factory.StartNew(s => ((IUsers)s).PutByuscIduserAsync(uscId, user), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='uscId'>
            /// </param>
            /// <param name='user'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PutByuscIduserAsync(this IUsers operations, string uscId, FaoUser user, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PutByuscIduserWithHttpMessagesAsync(uscId, user, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='uscId'>
            /// </param>
            public static object DeleteByuscId(this IUsers operations, string uscId)
            {
                return Task.Factory.StartNew(s => ((IUsers)s).DeleteByuscIdAsync(uscId), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='uscId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> DeleteByuscIdAsync(this IUsers operations, string uscId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DeleteByuscIdWithHttpMessagesAsync(uscId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='uscId'>
            /// </param>
            /// <param name='user'>
            /// </param>
            public static object PatchByuscIduser(this IUsers operations, string uscId, FaoUser user)
            {
                return Task.Factory.StartNew(s => ((IUsers)s).PatchByuscIduserAsync(uscId, user), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='uscId'>
            /// </param>
            /// <param name='user'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PatchByuscIduserAsync(this IUsers operations, string uscId, FaoUser user, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PatchByuscIduserWithHttpMessagesAsync(uscId, user, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static object Get(this IUsers operations)
            {
                return Task.Factory.StartNew(s => ((IUsers)s).GetAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetAsync(this IUsers operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='user'>
            /// </param>
            public static object PostByuser(this IUsers operations, FaoUser user)
            {
                return Task.Factory.StartNew(s => ((IUsers)s).PostByuserAsync(user), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='user'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PostByuserAsync(this IUsers operations, FaoUser user, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostByuserWithHttpMessagesAsync(user, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
