// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DataApiClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Application
    {
        /// <summary>
        /// Initializes a new instance of the Application class.
        /// </summary>
        public Application() { }

        /// <summary>
        /// Initializes a new instance of the Application class.
        /// </summary>
        public Application(int? id = default(int?), int? appNumber = default(int?), string term = default(string), string major = default(string), string classProperty = default(string), string owningUnit = default(string), string decisionCode = default(string), DateTime? decisionDate = default(DateTime?), Certification certification = default(Certification), bool? isCertifiable = default(bool?), bool? isWithdrawable = default(bool?), bool? hasAppeal = default(bool?), bool? isFreshmanTransfer = default(bool?), DateTime? removeDate = default(DateTime?), DateTime? withdrawDate = default(DateTime?))
        {
            Id = id;
            AppNumber = appNumber;
            Term = term;
            Major = major;
            ClassProperty = classProperty;
            OwningUnit = owningUnit;
            DecisionCode = decisionCode;
            DecisionDate = decisionDate;
            Certification = certification;
            IsCertifiable = isCertifiable;
            IsWithdrawable = isWithdrawable;
            HasAppeal = hasAppeal;
            IsFreshmanTransfer = isFreshmanTransfer;
            RemoveDate = removeDate;
            WithdrawDate = withdrawDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appNumber")]
        public int? AppNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "term")]
        public string Term { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "major")]
        public string Major { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "class")]
        public string ClassProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "owningUnit")]
        public string OwningUnit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "decisionCode")]
        public string DecisionCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "decisionDate")]
        public DateTime? DecisionDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "certification")]
        public Certification Certification { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isCertifiable")]
        public bool? IsCertifiable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isWithdrawable")]
        public bool? IsWithdrawable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasAppeal")]
        public bool? HasAppeal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isFreshmanTransfer")]
        public bool? IsFreshmanTransfer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "removeDate")]
        public DateTime? RemoveDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "withdrawDate")]
        public DateTime? WithdrawDate { get; set; }

    }
}
