// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DataApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Certification
    {
        /// <summary>
        /// Initializes a new instance of the Certification class.
        /// </summary>
        public Certification() { }

        /// <summary>
        /// Initializes a new instance of the Certification class.
        /// </summary>
        public Certification(bool? intentToEnroll = default(bool?), string intentReasonCode = default(string), string intentCeebCode = default(string), string intentOtherReason = default(string), string intentSchool = default(string), DateTime? submitDate = default(DateTime?), DateTime? removeDate = default(DateTime?), bool? hasFeeWaiver = default(bool?), string housingCode = default(string), string orientationCode = default(string), Waiver waiver = default(Waiver))
        {
            IntentToEnroll = intentToEnroll;
            IntentReasonCode = intentReasonCode;
            IntentCeebCode = intentCeebCode;
            IntentOtherReason = intentOtherReason;
            IntentSchool = intentSchool;
            SubmitDate = submitDate;
            RemoveDate = removeDate;
            HasFeeWaiver = hasFeeWaiver;
            HousingCode = housingCode;
            OrientationCode = orientationCode;
            Waiver = waiver;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "intentToEnroll")]
        public bool? IntentToEnroll { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "intentReasonCode")]
        public string IntentReasonCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "intentCeebCode")]
        public string IntentCeebCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "intentOtherReason")]
        public string IntentOtherReason { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "intentSchool")]
        public string IntentSchool { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "submitDate")]
        public DateTime? SubmitDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "removeDate")]
        public DateTime? RemoveDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasFeeWaiver")]
        public bool? HasFeeWaiver { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "housingCode")]
        public string HousingCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orientationCode")]
        public string OrientationCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "waiver")]
        public Waiver Waiver { get; set; }

    }
}
