// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DataApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FaoApp
    {
        /// <summary>
        /// Initializes a new instance of the FaoApp class.
        /// </summary>
        public FaoApp() { }

        /// <summary>
        /// Initializes a new instance of the FaoApp class.
        /// </summary>
        public FaoApp(int? id = default(int?), string name = default(string), string address = default(string), int? parentId = default(int?), int? orderId = default(int?))
        {
            Id = id;
            Name = name;
            Address = address;
            ParentId = parentId;
            OrderId = orderId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentId")]
        public int? ParentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderId")]
        public int? OrderId { get; set; }

    }
}
