// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace DataApiClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Waiver
    {
        /// <summary>
        /// Initializes a new instance of the Waiver class.
        /// </summary>
        public Waiver() { }

        /// <summary>
        /// Initializes a new instance of the Waiver class.
        /// </summary>
        public Waiver(string source = default(string), string verifyName = default(string), string verifyInstitute = default(string), string verifyInstituteCeebCode = default(string), string verifyPhone = default(string), string verifyEmail = default(string), string nai = default(string), string finHdshp = default(string), string remarks = default(string))
        {
            Source = source;
            VerifyName = verifyName;
            VerifyInstitute = verifyInstitute;
            VerifyInstituteCeebCode = verifyInstituteCeebCode;
            VerifyPhone = verifyPhone;
            VerifyEmail = verifyEmail;
            Nai = nai;
            FinHdshp = finHdshp;
            Remarks = remarks;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verifyName")]
        public string VerifyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verifyInstitute")]
        public string VerifyInstitute { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verifyInstituteCeebCode")]
        public string VerifyInstituteCeebCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verifyPhone")]
        public string VerifyPhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verifyEmail")]
        public string VerifyEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nai")]
        public string Nai { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "finHdshp")]
        public string FinHdshp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remarks")]
        public string Remarks { get; set; }

    }
}
