// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UvApi
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for FaoPWAidItems.
    /// </summary>
    public static partial class FaoPWAidItemsExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='term'>
            /// </param>
            /// <param name='uscid'>
            /// </param>
            /// <param name='tab'>
            /// </param>
            /// <param name='color'>
            /// </param>
            public static object Get(this IFaoPWAidItems operations, string term, string uscid, string tab, string color)
            {
                return operations.GetAsync(term, uscid, tab, color).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='term'>
            /// </param>
            /// <param name='uscid'>
            /// </param>
            /// <param name='tab'>
            /// </param>
            /// <param name='color'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetAsync(this IFaoPWAidItems operations, string term, string uscid, string tab, string color, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(term, uscid, tab, color, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
