// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DataApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Payment
    {
        /// <summary>
        /// Initializes a new instance of the Payment class.
        /// </summary>
        public Payment()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Payment class.
        /// </summary>
        public Payment(int? id = default(int?), string pid = default(string), int? appNum = default(int?), string term = default(string), int? appId = default(int?), System.DateTime? postDate = default(System.DateTime?), string resultCode = default(string), string authCode = default(string), string responseMessage = default(string), string transactionId = default(string))
        {
            Id = id;
            Pid = pid;
            AppNum = appNum;
            Term = term;
            AppId = appId;
            PostDate = postDate;
            ResultCode = resultCode;
            AuthCode = authCode;
            ResponseMessage = responseMessage;
            TransactionId = transactionId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pid")]
        public string Pid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appNum")]
        public int? AppNum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "term")]
        public string Term { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appId")]
        public int? AppId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postDate")]
        public System.DateTime? PostDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resultCode")]
        public string ResultCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "authCode")]
        public string AuthCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responseMessage")]
        public string ResponseMessage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionId")]
        public string TransactionId { get; set; }

    }
}
