// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DataApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Waiver
    {
        /// <summary>
        /// Initializes a new instance of the Waiver class.
        /// </summary>
        public Waiver()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Waiver class.
        /// </summary>
        public Waiver(string source = default(string), string verifyName = default(string), string verifyInstitute = default(string), string verifyInstituteCeebCode = default(string), string verifyPhone = default(string), string verifyEmail = default(string), string nai = default(string), string finHdshp = default(string), string remarks = default(string))
        {
            Source = source;
            VerifyName = verifyName;
            VerifyInstitute = verifyInstitute;
            VerifyInstituteCeebCode = verifyInstituteCeebCode;
            VerifyPhone = verifyPhone;
            VerifyEmail = verifyEmail;
            Nai = nai;
            FinHdshp = finHdshp;
            Remarks = remarks;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verifyName")]
        public string VerifyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verifyInstitute")]
        public string VerifyInstitute { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verifyInstituteCeebCode")]
        public string VerifyInstituteCeebCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verifyPhone")]
        public string VerifyPhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "verifyEmail")]
        public string VerifyEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nai")]
        public string Nai { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "finHdshp")]
        public string FinHdshp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remarks")]
        public string Remarks { get; set; }

    }
}
