// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UvApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AdmSAddContParameters
    {
        /// <summary>
        /// Initializes a new instance of the AdmSAddContParameters class.
        /// </summary>
        public AdmSAddContParameters()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AdmSAddContParameters class.
        /// </summary>
        public AdmSAddContParameters(string pid = default(string), string contactCode = default(string), string recruiterId = default(string), System.DateTime? contactDate = default(System.DateTime?), System.DateTime? sendDate = default(System.DateTime?), string operatorCode = default(string), System.DateTime? enteredDate = default(System.DateTime?))
        {
            Pid = pid;
            ContactCode = contactCode;
            RecruiterId = recruiterId;
            ContactDate = contactDate;
            SendDate = sendDate;
            OperatorCode = operatorCode;
            EnteredDate = enteredDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pid")]
        public string Pid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contactCode")]
        public string ContactCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recruiterId")]
        public string RecruiterId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contactDate")]
        public System.DateTime? ContactDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sendDate")]
        public System.DateTime? SendDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "operatorCode")]
        public string OperatorCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "enteredDate")]
        public System.DateTime? EnteredDate { get; set; }

    }
}
