// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace UvApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AdmSCasDenLoadParameters
    {
        /// <summary>
        /// Initializes a new instance of the AdmSCasDenLoadParameters class.
        /// </summary>
        public AdmSCasDenLoadParameters()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AdmSCasDenLoadParameters class.
        /// </summary>
        public AdmSCasDenLoadParameters(string pid = default(string), string term = default(string), string post = default(string), string options = default(string))
        {
            Pid = pid;
            Term = term;
            Post = post;
            Options = options;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pid")]
        public string Pid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "term")]
        public string Term { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "post")]
        public string Post { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "options")]
        public string Options { get; set; }

    }
}
